package com.minigoogle.crawler.heartbeat;

import com.minigoogle.crawler.model.CrawlTask;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import java.net.URI;
import java.time.Duration;
import java.time.Instant;
import java.util.Map;

import static org.junit.jupiter.api.Assertions.*;

/** Tests for WorkerHeartbeat functionality. */
class WorkerHeartbeatTest {

    private WorkerHeartbeat heartbeat;

    @BeforeEach
    void setUp() {
        heartbeat = new WorkerHeartbeat("worker-1", Duration.ofSeconds(5));
    }

    @Test
    void testInitialState() {
        assertTrue(heartbeat.isAlive());
        assertEquals("worker-1", heartbeat.getWorkerId());
        assertNull(heartbeat.getCurrentTask());
        assertEquals(0, heartbeat.getTotalTasksCompleted());
        assertEquals(0, heartbeat.getTotalTasksFailed());
    }

    @Test
    void testTickRefreshesHeartbeat() throws InterruptedException {
        Thread.sleep(100);
        heartbeat.tick();
        assertTrue(heartbeat.isAlive());
        assertTrue(heartbeat.timeSinceLastHeartbeat().toMillis() < 200);
    }

    @Test
    void testIsAliveTimeout() throws InterruptedException {
        WorkerHeartbeat shortTimeout = new WorkerHeartbeat("worker-2", Duration.ofMillis(50));
        assertTrue(shortTimeout.isAlive());

        Thread.sleep(100);
        assertFalse(shortTimeout.isAlive());
    }

    @Test
    void testStartTask() {
        CrawlTask task = new CrawlTask(URI.create("https://example.com"), "example.com", 0, Instant.now());
        heartbeat.startTask(task);

        assertNotNull(heartbeat.getCurrentTask());
        assertEquals("https://example.com", heartbeat.getCurrentTask().getUrl().toString());
    }

    @Test
    void testCompleteTask() {
        CrawlTask task = new CrawlTask(URI.create("https://example.com"), "example.com", 0, Instant.now());
        heartbeat.startTask(task);
        heartbeat.completeTask();

        assertNull(heartbeat.getCurrentTask());
        assertEquals(1, heartbeat.getTotalTasksCompleted());
    }

    @Test
    void testFailTask() {
        CrawlTask task = new CrawlTask(URI.create("https://example.com"), "example.com", 0, Instant.now());
        heartbeat.startTask(task);
        heartbeat.failTask();

        assertNull(heartbeat.getCurrentTask());
        assertEquals(1, heartbeat.getTotalTasksFailed());
    }

    @Test
    void testGetStatus() {
        CrawlTask task = new CrawlTask(URI.create("https://example.com"), "example.com", 0, Instant.now());
        heartbeat.startTask(task);

        Map<String, Object> status = heartbeat.getStatus();
        assertEquals("worker-1", status.get("workerId"));
        assertEquals(true, status.get("alive"));
        assertEquals("https://example.com", status.get("currentTask"));
        assertEquals(0L, status.get("completedTasks"));
        assertEquals(0L, status.get("failedTasks"));
    }

    @Test
    void testGetStatusNoTask() {
        Map<String, Object> status = heartbeat.getStatus();
        assertEquals("none", status.get("currentTask"));
    }

    @Test
    void testMultipleTaskCycles() {
        CrawlTask task1 = new CrawlTask(URI.create("https://a.com"), "a.com", 0, Instant.now());
        CrawlTask task2 = new CrawlTask(URI.create("https://b.com"), "b.com", 0, Instant.now());

        heartbeat.startTask(task1);
        heartbeat.completeTask();
        heartbeat.startTask(task2);
        heartbeat.completeTask();

        assertEquals(2, heartbeat.getTotalTasksCompleted());
        assertEquals(0, heartbeat.getTotalTasksFailed());
    }

    @Test
    void testAutoGeneratedWorkerId() {
        WorkerHeartbeat autoId = new WorkerHeartbeat(Duration.ofSeconds(5));
        assertNotNull(autoId.getWorkerId());
        assertFalse(autoId.getWorkerId().isEmpty());
    }

    @Test
    void testGetTimeout() {
        assertEquals(Duration.ofSeconds(5), heartbeat.getTimeout());
    }
}
